name: Run jadwalflash.py

on:
  schedule:
    - cron: '0 17 * * *'  # Setiap hari jam 00:00 WIB (17:00 UTC)
  workflow_dispatch:

env:
  TZ: Asia/Jakarta
  LC_ALL: C.UTF-8
  LANG: C.UTF-8

jobs:
  run-jadwalflash:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    
    - name: Set WIB Timezone
      uses: szenius/set-timezone@v2.0
      with:
        timezoneLinux: "Asia/Jakarta"
    
    - name: Install Chrome and ChromeDriver
      run: |
        # Hapus chromedriver lama jika ada untuk menghindari konflik
        sudo rm -f /usr/bin/chromedriver
        
        # Install Chrome
        sudo apt-get update
        sudo apt-get install -y wget unzip
        wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
        echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable

        # Install ChromeDriver
        CHROME_VERSION=$(google-chrome --version | awk '{print $3}' | cut -d. -f1-3)
        CHROMEDRIVER_VERSION=$(wget -qO- https://chromedriver.storage.googleapis.com/LATEST_RELEASE_${CHROME_VERSION%%.*})
        wget -q "https://chromedriver.storage.googleapis.com/${CHROMEDRIVER_VERSION}/chromedriver_linux64.zip"
        unzip -q chromedriver_linux64.zip
        sudo mv chromedriver /usr/local/bin/chromedriver
        sudo chmod +x /usr/local/bin/chromedriver
        rm chromedriver_linux64.zip

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Configure Git
      run: |
        git config --global user.name 'GitHub Actions Bot'
        git config --global user.email 'actions@users.noreply.github.com'
    
    - name: Run jadwalflash.py
      run: |
        TIMESTAMP=$(TZ='Asia/Jakarta' date +"%Y%m%d_%H%M%S")
        LOG_FILE="logs/jadwalflash_${TIMESTAMP}.log"
        mkdir -p logs
        # Menambahkan /usr/local/bin ke PATH untuk memastikan chromedriver yang benar digunakan
        export PATH="/usr/local/bin:$PATH"
        python jadwalflash.py 2>&1 | tee "$LOG_FILE"
    
    - name: Commit and push changes
      run: |
        git add .
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update jadwalflash data" && git push)
