name: Run jadwalflash.py

on:
  schedule:
    - cron: '0 17 * * *'  # Setiap hari jam 00:00 WIB (17:00 UTC)
  workflow_dispatch:

env:
  TZ: Asia/Jakarta
  LC_ALL: C.UTF-8
  LANG: C.UTF-8

jobs:
  run-jadwalflash:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    
    - name: Set WIB Timezone
      uses: szenius/set-timezone@v2.0
      with:
        timezoneLinux: "Asia/Jakarta"
    
    - name: Set up Chrome and ChromeDriver
      uses: browser-actions/setup-chrome@v1
      with:
        chrome-version: stable
    
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Configure Git
      run: |
        git config --global user.name 'GitHub Actions Bot'
        git config --global user.email 'actions@users.noreply.github.com'
    
    - name: Run jadwalflash.py
      run: |
        TIMESTAMP=$(TZ='Asia/Jakarta' date +"%Y%m%d_%H%M%S")
        LOG_FILE="logs/jadwalflash_${TIMESTAMP}.log"
        mkdir -p logs
        python jadwalflash.py 2>&1 | tee "$LOG_FILE"
    
    - name: Commit and push changes
      run: |
        git add .
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update jadwalflash data" && git push)
