name: Scheduled Scraping Scripts

on:
  schedule:
    - cron: '0 17 * * *'  # jadwalflash.py - setiap hari jam 00:00 WIB (17:00 UTC)
    - cron: '*/30 * * * *'  # rereyano.py dan sportsonline.py - setiap 30 menit
    - cron: '*/15 * * * *'  # inplaynet.py dan sch.py - setiap 15 menit
  workflow_dispatch:

# Atur zona waktu default ke Jakarta
env:
  TZ: Asia/Jakarta
  LC_ALL: C.UTF-8
  LANG: C.UTF-8

jobs:
  run-scrapers:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'  # Menggunakan Python 3.10 untuk kompatibilitas yang lebih baik
    
    - name: Set timezone to Jakarta
      run: |
        sudo timedatectl set-timezone Asia/Jakarta
        echo "Zona waktu saat ini: $(date)"
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y tzdata
        sudo ln -fs /usr/share/zoneinfo/Asia/Jakarta /etc/localtime
        sudo dpkg-reconfigure --frontend noninteractive tzdata
        sudo apt-get install -y chromium-browser chromium-chromedriver
    
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Configure Git
      run: |
        git config --global user.name 'GitHub Actions Bot'
        git config --global user.email 'actions@users.noreply.github.com'
    
    - name: Set up Chrome options for Selenium
      run: |
        echo "CHROME_BIN=/usr/bin/chromium-browser" >> $GITHUB_ENV
        echo "CHROMEDRIVER_PATH=/usr/lib/chromium-browser/chromedriver" >> $GITHUB_ENV
    
    - name: Run scraping scripts
      id: scrape
      env:
        CHROME_BIN: /usr/bin/chromium-browser
        CHROMEDRIVER_PATH: /usr/lib/chromium-browser/chromedriver
        TZ: Asia/Jakarta  # Pastikan script Python menggunakan zona waktu yang benar
      run: |
        set -e
        
        # Tampilkan waktu saat ini di Jakarta
        echo "Waktu saat ini di Jakarta: $(TZ='Asia/Jakarta' date)"
        
        # Buat direktori untuk log
        mkdir -p logs
        
        # Fungsi untuk menjalankan script dengan logging
        run_script() {
          local script=$1
          local timestamp=$(TZ='Asia/Jakarta' date +"%Y%m%d_%H%M%S")
          local log_file="logs/${script%.*}_${timestamp}.log"
          
          echo "Menjalankan $script..."
          if TZ='Asia/Jakarta' python "$script" 2>&1 | tee "$log_file"; then
            echo "$script selesai dengan sukses"
            return 0
          else
            echo "Error saat menjalankan $script"
            return 1
          fi
        }
        
        # Jalankan script sesuai jadwal
        if [[ "${{ github.event.schedule }}" == "0 17 * * *" ]]; then
          run_script "jadwalflash.py"
        fi
        
        if [[ "${{ github.event.schedule }}" == "*/30 * * * *" ]]; then
          run_script "rereyano.py"
          run_script "sportsonline.py"
        fi
        
        if [[ "${{ github.event.schedule }}" == "*/15 * * * *" ]]; then
          run_script "inplaynet.py"
          run_script "sch.py"
        fi
        
        # Periksa perubahan pada file JSON
        echo "File yang berubah:"
        git status -s
    
    - name: Commit and push changes
      if: success() && steps.scrape.outcome == 'success'
      run: |
        # Atur zona waktu untuk commit
        git config --global log.date local
        # Tambahkan semua file JSON yang berubah
        git add *.json sch/*.json translate/*.json
        
        # Commit hanya jika ada perubahan
        if ! git diff --staged --quiet; then
          git commit -m "Auto-update: Data scraping terbaru [skip ci]" --date="$(TZ='Asia/Jakarta' date)"
          git push
        else
          echo "Tidak ada perubahan pada file JSON"
        fi
    
    - name: Upload artifacts
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: scraping-outputs
        path: |
          *.json
          sch/*.json
          translate/*.json
          logs/
        retention-days: 7
    
    - name: Notify on failure
      if: failure()
      uses: actions/github-script@v6
      with:
        script: |
          const { data } = await github.rest.issues.createComment({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: context.issue.number,
            body: `❌ Scraping gagal pada workflow ${{ github.workflow }} (Waktu Jakarta: ${new Date().toLocaleString('id-ID', { timeZone: 'Asia/Jakarta' })}).\nSilakan periksa log untuk detail lebih lanjut.`
          })
